# Use an official Python runtime as base image
FROM ubuntu:22.04

# Set the working directory in the container
WORKDIR /task

# Copy the current directory contents into the container at /app
COPY . /

RUN pip install opencv
RUN pip install scikit-image
RUN pip install scipy
RUN pip install matplotlib
RUN pip install numpy
RUN pip install matplotlib
RUN pip install random
RUN pip install math
RUN pip install vizdoom